version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///data/archimvc.db
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
